# Generated by Django 3.2 on 2022-10-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('DATABASE', 'DATABASE'), ('QUERY', 'QUERY')], default='QUERY', max_length=50)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
